### ISSUE TITLE
Keep getting 5008

### ISSUE THREAD

**Issue by ridewiththewind** [faceki/blaze-android-sdk#1]
Hi, is the API all ready? Because I keep getting {"status":false,"code":5008,"message":"FAILED","appVersion":"v3.0.0","result":"Unable to Process the document [id]"}

I've follow your documentation on https://docs.faceki.com/api-integration/verification-apis/face-match-api

Tried postman, i am able to get the access token, but I fail calling this URL:

1. https://sdk.faceki.com/api/v3/kyc_verification

Please assist, thank you.

**Comment by faceki** [comment]
All the APIs are operational, kindly contact the relationship manager so they can help you in getting in touch with tech support. Thanks
